AllCops:
  NewCops: enable
  Exclude:
    - 'Guardfile'
    - 'Rakefile'
    - 'node_modules/**/*'

  DisplayCopNames: true

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 48
Metrics/AbcSize:
  Max: 80
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  AllowedMethods: ['describe']
  Max: 30
Metrics/PerceivedComplexity:
  Max: 30

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/HashAlignment:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: crlf
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
